### ISSUE TITLE
Maximum wait time has been exceeded.

### ISSUE THREAD

**Issue by leotaglia** [stephenpearson/kitchen-oci#31]
When executing `kitchen create` I get "Maximum wait time has been exceeded." in the same environment as worked in the past. I tested it with proxy and in other environment and other OSes with direct connection, same issue. Maybe Oracle changed something.

Executing `telnet iaas.us-ashburn-1.oraclecloud.com 443` connects.

```
ping iaas.us-ashburn-1.oraclecloud.com

Pinging splat-api.us-ashburn-1.oci.oraclecloud.com [140.91.12.32] with 32 bytes of data:
Reply from 140.91.12.32: bytes=32 time=166ms TTL=53
Reply from 140.91.12.32: bytes=32 time=163ms TTL=53
Reply from 140.91.12.32: bytes=32 time=165ms TTL=53
Reply from 140.91.12.32: bytes=32 time=162ms TTL=53
```

```
-----> Creating <chef-lx>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Maximum wait time has been exceeded.] on chef-lx
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Maximum wait time has been exceeded.] on chef-lx
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:181:in `report_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:172:in `run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command/action.rb:35:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command/action.rb:33:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/cli.rb:52:in `perform'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/bin/kitchen:11:in `block in <top (required)>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/errors.rb:170:in `with_friendly_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/bin/kitchen:11:in `<top (required)>'
D      C:/opscode/chefdk/bin/kitchen:358:in `load'
D      C:/opscode/chefdk/bin/kitchen:358:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [Maximum wait time has been exceeded.] on chef-lx
D      ----------------------
D      ------Backtrace-------
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/waiter.rb:136:in `block in wait_until'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/waiter.rb:129:in `loop'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/waiter.rb:129:in `wait_until'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:269:in `launch_compute_instance'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:194:in `launch_instance'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:73:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `block in perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:524:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:523:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:404:in `create_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:391:in `block in transition_to'D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:128:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [Maximum wait time has been exceeded.]
D      ----------------------
D      ------Backtrace-------
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/waiter.rb:136:in `block in wait_until'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:269:in `launch_compute_instance'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:194:in `launch_instance'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:73:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `block in perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:524:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:404:in `create_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:391:in `block in transition_to'D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:128:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:166:in `block (2 levels) in run_D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
```

**Comment by leotaglia** [comment]
Also sometimes I'm getting `Too many requests for the user` but never gets to finish the creation.


```
-----> Creating <chef-lx>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Too many requests for the user] on chef-lx
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Too many requests for the user] on chef-lx
D      ----------------------
D      ------Backtrace-------
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:181:in `report_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:172:in `run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command/action.rb:35:in `block in call'
D      C:/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command/action.rb:33:in `call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/cli.rb:52:in `perform'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/bin/kitchen:11:in `block in <top (required)>'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/errors.rb:170:in `with_friendly_errors'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/bin/kitchen:11:in `<top (required)>'
D      C:/opscode/chefdk/bin/kitchen:358:in `load'
D      C:/opscode/chefdk/bin/kitchen:358:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [Too many requests for the user] on chef-lx
D      ----------------------
D      ------Backtrace-------
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/api_client.rb:478:in `handle_non_success_response'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/api_client.rb:390:in `call_api_inner'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/api_client.rb:143:in `block in call_api'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/waiter.rb:149:in `block in wait_until'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/waiter.rb:129:in `loop'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/waiter.rb:129:in `wait_until'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:269:in `launch_compute_instance'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:194:in `launch_instance'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:73:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `block in perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:524:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:523:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:404:in `create_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:391:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:128:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [Too many requests for the user]
D      ----------------------
D      ------Backtrace-------
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/api_client.rb:478:in `handle_non_success_response'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/api_client.rb:390:in `call_api_inner'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/api_client.rb:143:in `block in call_api'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/waiter.rb:149:in `block in wait_until'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/waiter.rb:129:in `loop'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/oci-2.14.0/lib/oci/waiter.rb:129:in `wait_until'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:269:in `launch_compute_instance'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:194:in `launch_instance'
D      C:/Users/LeonardoTagliabue/AppData/Local/chefdk/gem/ruby/2.6.0/gems/kitchen-oci-1.12.0/lib/kitchen/driver/oci.rb:73:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `block in perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:563:in `synchronize_or_call'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:524:in `block in action'
D      C:/opscode/chefdk/embedded/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:523:in `action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:495:in `perform_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:404:in `create_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:392:in `block (2 levels) in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:391:in `block in transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `each'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:390:in `transition_to'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/instance.rb:128:in `create'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `public_send'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:195:in `run_action_in_thread'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/test-kitchen-2.8.0/lib/kitchen/command.rb:166:in `block (2 levels) in run_action'
D      C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/logging-2.3.0/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
D      ----End Backtrace-----
```

**Comment by leotaglia** [comment]
This was for another error, sorry.
